# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml

name: Multi-Platform CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  # ==========================================
  # JOB 1: LINUX BUILD
  # ==========================================
  build-linux:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev qt6-svg-dev qt6-tools-dev libtag1-dev libgtest-dev

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build Project
      run: cmake --build build --config Release

    - name: Run Tests
      run: ctest --test-dir build --build-config Release --output-on-failure



  # ==========================================
  # JOB 2: WINDOWS BUILD
  # ==========================================
  build-windows:
    name: Windows (MSYS2 MinGW)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up MSYS2 & Install Dependencies
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          mingw-w64-ucrt-x86_64-cc
          mingw-w64-ucrt-x86_64-qt6-base
          mingw-w64-ucrt-x86_64-taglib
          mingw-w64-ucrt-x86_64-gtest

    - name: Configure CMake
      shell: msys2 {0}
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build Project
      shell: msys2 {0}
      run: cmake --build build --config Release

    - name: Run Tests
      shell: msys2 {0}
      run: ctest --test-dir build --build-config Release --output-on-failure
